baseURL = 'https://hagachan.pages.dev/'
languageCode = 'ja-jp'
title = '初めてのブログ'
theme = 'mainroad'

[params]
  description = "John Doe's Personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information

 [Author]
  

  